# Test configuration for Token API
clusters:
  default:
    url: http://127.0.0.1:8123
    username: default
    password: ""

networks:
  mainnet:
    type: evm
    cluster: default
    transfers: mainnet:evm-transfers@v0.2.2
    balances: mainnet:evm-balances@v0.2.3
    nfts: mainnet:evm-nft-tokens@v0.6.2
    dexes: mainnet:evm-dex@v0.2.6
    contracts: mainnet:evm-contracts@v0.3.0

  solana:
    type: svm
    cluster: default
    transfers: solana:solana-tokens@v0.2.8
    balances: solana:solana-tokens@v0.2.8
    dexes: solana:svm-dex@v0.3.1

  tron:
    type: tvm
    cluster: default
    transfers: tron:evm-transfers@v0.2.3
    dexes: tron:evm-dex@v0.2.6
